server:
  port: 18090
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  thymeleaf:
    cache: false
  redis:
    host: 172.16.116.100
  datasource:
    url: jdbc:mysql://172.16.116.100:3306/guli_cart
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  task:
    execution:
      thread-name-prefix: cart-async-
      pool:
        core-size: 100
        max-size: 200
        queue-capacity: 5000
        keep-alive: 60s
        allow-core-thread-timeout: true
      shutdown:
        await-termination: true
        await-termination-period: 100
  rabbitmq:
    host: 172.16.116.100
    virtual-host: /fengge
    username: fengge
    password: fengge
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 1
        concurrency: 3
feign:
  sentinel:
    enabled: true
jwt:
  pubKeyPath: D:\project-0316\rsa\rsa.pub
  cookieName: GMALL_TOKEN
  userKeyName: user-key
  expire: 15552000
